(ns clap.main-test
  (:use [cljd.test :only [deftest is]]
        [clap.widget-helper :only [deftest-widget should-find-one]])
  (:require ["package:flutter/material.dart" :as m]
            [clap.widget-helper :as helper]
            [clap.main :as sut]))

(deftest-widget welcome-to-clojure [{:keys [pumpWidget]}]
  (await (pumpWidget (sut/app)))
  (should-find-one (helper/find-text "Welcome to ClojureDart")))

(deftest-widget lets-get-coding [{:keys [pumpWidget widget]}]
  (await (pumpWidget (sut/app)))
  (let [finder (helper/find-text "Let's get coding!")
        widget (widget finder)]
    (should-find-one finder)
    (is (= 32.0 (helper/font-size widget)))
    (is (= m.Colors/red (helper/color widget)))))
